### ISSUE TITLE
Says WebRTC not available on WebRTC capable browser

### ISSUE THREAD

**Issue by bodavid** [netCommonsEU/PeerStreamer-ng#13]
This is due to WebRTC having changed the API, which it often does. See https://developer.mozilla.org/en-US/docs/Web/API/Navigator/getUserMedia
I tried Edge, Chrome and Firefox on Windows.
I fixed it in my pull request but it also requires https.

**Comment by lucabaldesi** [comment]
Moved in the #14 thread.
